import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

/**
 * 💎 Live Intelligence Dashboard (Phase 8)
 * 
 * Visualizes the backend's "Legendary" intelligence in real-time:
 * - AI Revenue Surplus (The direct profit generated by ML)
 * - Live Pulse (Real-time viewer competition)
 * - A/B Tournament Stats (Model A vs Model B)
 */

const LiveIntelligence = ({ eventId }) => {
  const [stats, setStats] = useState({
    surplus: 0,
    viewers: 0,
    activeModel: 'Model A (Stable)',
    health: 'Excellent'
  });

  // Simulate WebSocket updates (In real life, this connects to notification.ws.js)
  useEffect(() => {
    const interval = setInterval(() => {
      setStats(prev => ({
        ...prev,
        surplus: prev.surplus + Math.floor(Math.random() * 50),
        viewers: 20 + Math.floor(Math.random() * 15)
      }));
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="cyber-grid" style={{ marginBottom: '2rem' }}>
      {/* 🚀 AI REVENUE SURPLUS */}
      <motion.div 
        className="cyber-card"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        style={{ borderLeft: '4px solid var(--success)', boxShadow: 'var(--diamond-glow)' }}
      >
        <div className="cyber-label">AI Revenue Surplus</div>
        <div className="title-main" style={{ fontSize: '2rem', margin: '0.5rem 0' }}>
          ₹{stats.surplus.toLocaleString()}
        </div>
        <div className="text-muted" style={{ fontSize: '0.8rem' }}>
          Direct profit generated by Dynamic Pricing
        </div>
        <div className="cyber-badge badge-success" style={{ marginTop: '1rem' }}>
          📈 +12% Growth
        </div>
      </motion.div>

      {/* 💓 LIVE PULSE (FOMO) */}
      <motion.div 
        className="cyber-card"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
      >
        <div className="cyber-label">Live Audience</div>
        <div className="flex-between" style={{ marginTop: '0.5rem' }}>
          <div className="title-main" style={{ fontSize: '2rem', margin: 0 }}>
            {stats.viewers}
          </div>
          <div className="cyber-pulse" style={{ 
            width: '12px', height: '12px', 
            borderRadius: '50%', backgroundColor: 'var(--danger)',
            boxShadow: '0 0 10px var(--danger)'
          }} />
        </div>
        <div className="text-muted" style={{ fontSize: '0.8rem' }}>
          Real-time viewers competing for seats
        </div>
        <div className="text-gradient" style={{ fontWeight: 'bold', marginTop: '1rem' }}>
          🔥 High Demand Detected
        </div>
      </motion.div>

      {/* 🧠 A/B TOURNAMENT STATUS */}
      <motion.div 
        className="cyber-card"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <div className="cyber-label">A/B Tournament</div>
        <div className="text-main" style={{ fontWeight: 'bold', marginTop: '0.5rem' }}>
          Winning: {stats.activeModel}
        </div>
        <div style={{ marginTop: '1rem', height: '8px', background: 'var(--bg-accent)', borderRadius: '4px', overflow: 'hidden' }}>
          <motion.div 
            initial={{ width: '0%' }}
            animate={{ width: '70%' }}
            style={{ height: '100%', background: 'var(--accent-cyan)' }}
          />
        </div>
        <div className="flex-between" style={{ marginTop: '0.5rem', fontSize: '0.7rem' }}>
          <span className="text-muted">Model A: 70%</span>
          <span className="text-muted">Model B: 30%</span>
        </div>
      </motion.div>
    </div>
  );
};

export default LiveIntelligence;
