FROM node:22-bookworm

ARG SERVICE_PATH
ARG PORT

WORKDIR /app

COPY shared ./shared
COPY ${SERVICE_PATH} ./${SERVICE_PATH}

RUN cd shared && npm install
RUN cd ${SERVICE_PATH} && npm install

WORKDIR /app/${SERVICE_PATH}

ENV NODE_ENV=production
ENV PORT=${PORT}

EXPOSE ${PORT}

CMD ["node","index.js"]
